//Funciones para cambiar los parrafos del popup en el mapa interactivo
function Punto1() {
	document.getElementById("Info").innerHTML = '<img class="imgM" src="images/CMS.jpg" alt="punto uno"><br><span>DETECTOR CMS</span><br><br>Las siglas son por "Compact Muon Solenoid". El objetivo del experimento CMS es investigar una amplia gama de física, incluida la búsqueda del bosón de Higgs, las dimensiones extra y las partículas que podrían constituir la materia oscura. El CMS tiene 21 metros de largo, 15 m de diámetro y pesa unas 14.000 toneladas. Más de 4.000 personas, que representan a 206 institutos científicos y 47 países, forman la colaboración del CMS que construyó y ahora opera el detector.';
}
function Punto2() {
	document.getElementById("Info").innerHTML = '<img class="imgM" src="images/LHCb.jpg" alt="punto dos"><br><span>DETECTOR LHCb</span><br><br>LHCb es un experimento especializado en física del quark b, diseñado principalmente para medir los parámetros de violación de CP en las interacciones de los b-hadrones (partículas pesadas que contienen un quark inferior). Estos estudios pueden ayudar a explicar la asimetría materia-antimateria del Universo. El detector también puede realizar mediciones de las secciones transversales de producción, espectroscopia de hadrones exóticos, física del encanto y física electrodébil en la región delantera';
}
function Punto3() {
	document.getElementById("Info").innerHTML = '<img class="imgM" src="images/ATLAS.jpg" alt="punto tres"><br><span>DETECTOR ATLAS</span><br><br>ATLAS fue uno de los dos experimentos del LHC que participaron en el descubrimiento del bosón de Higgs en julio de 2012 También fue diseñado para buscar pruebas de teorías de la física de partículas más allá del Modelo Estándar. El experimento es una colaboración en la que participan 5.767 miembros, de los cuales 2.646 son físicos (último censo: 9 de septiembre de 2021) de 180 instituciones de 40 países.';
}
function Punto4() {
	document.getElementById("Info").innerHTML = '<img class="imgM" src="images/ALICE.jpg" alt="punto cuatro"><br><span>DETECTOR ALICE</span><br><br>ALICE está optimizado para estudiar las colisiones de iones pesados (núcleos Pb-Pb) a una energía del centro de masa de hasta 5,02 TeV por par de nucleones. La temperatura y la densidad de energía resultantes permiten explorar el plasma de quarks-gluones, un quinto estado de la materia en el que se liberan quarks y gluones. Se cree que existían condiciones similares una fracción de segundo después del Big Bang, antes de que los quarks y los gluones se unieran para formar hadrones y partículas más pesadas.';
}
